# Generated by Django 3.1.1 on 2020-09-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200916_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
